# These limits are used by MoveIt and augment/override the definitions in
# ur_description.
joint_limits:
  joint_1:
    has_acceleration_limits: true
    max_acceleration: 0.16 # 5 deg/s^2
    has_velocity_limits: true
    max_velocity: 0.8
  joint_2:
    has_acceleration_limits: true
    max_acceleration: 0.16 # 5 deg/s^2
    has_velocity_limits: true
    max_velocity: 0.8
  joint_3:
    has_acceleration_limits: true
    max_acceleration: 0.16 # 5 deg/s^2
    has_velocity_limits: true
    max_velocity: 0.8
  joint_4:
    has_acceleration_limits: true
    max_acceleration: 0.16 # 5 deg/s^2
    has_velocity_limits: true
    max_velocity: 0.8
  joint_5:
    has_acceleration_limits: true
    max_acceleration: 0.16 # 5 deg/s^2
    has_velocity_limits: true
    max_velocity: 0.8
  joint_6:
    has_acceleration_limits: true
    max_acceleration: 0.16 # 5 deg/s^2
    has_velocity_limits: true
    max_velocity: 0.8
  gripper_jaw1_joint:
    has_acceleration_limits: true
    max_acceleration: 0.01 # m/s^2
    has_velocity_limits: true
    max_velocity: 0.02 # m/s
